export interface AvailablePlayer {
  id: string;
  name: string;
  position: string;
  age: number;
  country: string;
  level: string;
  status: string;
  trend: "Improving" | "Declining";
  image: string;
  bio: string;
  stats: {
    appearances: number;
    goals: number;
    assists: number;
    minutesPlayed: string;
    shotsOnTarget: number;
    passAccuracy: string;
  };
  strengths: string[];
  areasToImprove: string[];
  contractStatus: string;
  relocation: boolean;
  preferredLeagues: string[];
}

export const availablePlayers: AvailablePlayer[] = [
  {
    id: "LP-772",
    name: "Lucas Martinez",
    position: "Forward",
    age: 23,
    country: "Spain",
    level: "Semi-Pro",
    status: "Open to trials",
    trend: "Improving",
    image: "https://i.pravatar.cc/150?u=lucas",
    bio: "Dynamic forward with excellent pace and finishing ability. Strong work ethic and team player mentality.",
    stats: {
      appearances: 28,
      goals: 15,
      assists: 8,
      minutesPlayed: "2,340",
      shotsOnTarget: 42,
      passAccuracy: "78%",
    },
    strengths: [
      "Excellent positioning",
      "Strong finishing with both feet",
      "High work rate",
    ],
    areasToImprove: [
      "Link-up play with midfielders",
      "Decision making",
      "Consistency",
    ],
    contractStatus: "Free Agent - Available Immediately",
    relocation: true,
    preferredLeagues: ["Championship", "League One"],
  },
  {
    id: "LP-881",
    name: "Marco Silva",
    position: "Midfielder",
    age: 21,
    country: "Portugal",
    level: "Pro",
    status: "Available",
    trend: "Improving",
    image: "https://i.pravatar.cc/150?u=marco",
    bio: "Technical midfielder with exceptional vision and passing range. Influential in build-up play and set-pieces.",
    stats: {
      appearances: 32,
      goals: 4,
      assists: 12,
      minutesPlayed: "2,850",
      shotsOnTarget: 18,
      passAccuracy: "88%",
    },
    strengths: [
      "Visionary passing",
      "Set-piece specialist",
      "Calm under pressure",
    ],
    areasToImprove: ["Defensive work rate", "Aerial duels", "Stamina"],
    contractStatus: "Available - Subject to compensation",
    relocation: true,
    preferredLeagues: ["Premier League", "La Liga"],
  },
  {
    id: "LP-903",
    name: "Jean Dupont",
    position: "Defender",
    age: 25,
    country: "France",
    level: "Senior",
    status: "Contract expiring",
    trend: "Improving",
    image: "https://i.pravatar.cc/150?u=jean",
    bio: "Commanding center-back with strong leadership qualities. Exceptional at reading the game and aerial challenges.",
    stats: {
      appearances: 25,
      goals: 2,
      assists: 1,
      minutesPlayed: "2,250",
      shotsOnTarget: 5,
      passAccuracy: "82%",
    },
    strengths: ["Leadership", "Aerial dominance", "Interception"],
    areasToImprove: [
      "Speed over long distances",
      "Long ball accuracy",
      "Tackling timing",
    ],
    contractStatus: "Contract Expiring June 2024",
    relocation: false,
    preferredLeagues: ["Ligue 1", "Bundesliga"],
  },
  {
    id: "LP-104",
    name: "Hans Müller",
    position: "Goalkeeper",
    age: 27,
    country: "Germany",
    level: "Experienced",
    status: "Open to trials",
    trend: "Declining",
    image: "https://i.pravatar.cc/150?u=hans",
    bio: "Reliable goalkeeper with excellent reflex saves and distribution. High concentration levels throughout the match.",
    stats: {
      appearances: 30,
      goals: 0,
      assists: 0,
      minutesPlayed: "2,700",
      shotsOnTarget: 0,
      passAccuracy: "65%",
    },
    strengths: ["Shot-stopping", "Box command", "Concentration"],
    areasToImprove: [
      "Penalty area communication",
      "High ball handling",
      "One-on-one situations",
    ],
    contractStatus: "Free Agent",
    relocation: true,
    preferredLeagues: ["Bundesliga 2", "Eredivisie"],
  },
  {
    id: "LP-552",
    name: "Andre Santos",
    position: "Forward",
    age: 22,
    country: "Brazil",
    level: "Rising Star",
    status: "Available",
    trend: "Improving",
    image: "https://i.pravatar.cc/150?u=andre",
    bio: "Flair-filled forward capable of moments of magic. Great dribbling and ability to beat defenders.",
    stats: {
      appearances: 20,
      goals: 12,
      assists: 5,
      minutesPlayed: "1,600",
      shotsOnTarget: 35,
      passAccuracy: "74%",
    },
    strengths: ["Dribbling", "Acceleration", "Unpredictability"],
    areasToImprove: ["Tactical discipline", "Strength", "Crossing"],
    contractStatus: "Available for Transfer",
    relocation: true,
    preferredLeagues: ["Serie A", "Primeira Liga"],
  },
  {
    id: "LP-334",
    name: "Koji Yamato",
    position: "Midfielder",
    age: 24,
    country: "Japan",
    level: "Semi-Pro",
    status: "Seeking Team",
    trend: "Improving",
    image: "https://i.pravatar.cc/150?u=koji",
    bio: "Hard-working box-to-box midfielder with great engine and technical proficiency. Covers a lot of ground.",
    stats: {
      appearances: 26,
      goals: 3,
      assists: 4,
      minutesPlayed: "2,100",
      shotsOnTarget: 12,
      passAccuracy: "85%",
    },
    strengths: ["Stamina", "Technical skills", "Ball recovery"],
    areasToImprove: ["Goal-scoring", "Final third decision making", "Strength"],
    contractStatus: "Free Agent",
    relocation: true,
    preferredLeagues: ["J-League", "MLS"],
  },
  {
    id: "LP-441",
    name: "Kevin De Jong",
    position: "Defender",
    age: 26,
    country: "Netherlands",
    level: "Senior Pro",
    status: "Free Agent",
    trend: "Improving",
    image: "https://i.pravatar.cc/150?u=kevin",
    bio: "Intelligent full-back with attacking instinct and defensive solidity. Good crossing and positional sense.",
    stats: {
      appearances: 24,
      goals: 1,
      assists: 6,
      minutesPlayed: "2,160",
      shotsOnTarget: 8,
      passAccuracy: "79%",
    },
    strengths: ["Crossing", "Positional awareness", "Recovery speed"],
    areasToImprove: ["Aerial duels", "Shooting", "1v1 defending"],
    contractStatus: "Free Agent",
    relocation: true,
    preferredLeagues: ["Eredivisie", "Super Lig"],
  },
  {
    id: "LP-228",
    name: "Samuel Eto",
    position: "Striker",
    age: 20,
    country: "Cameroon",
    level: "Prospect",
    status: "Available",
    trend: "Improving",
    image: "https://i.pravatar.cc/150?u=samuel",
    bio: "Fast and explosive striker with a keen eye for goal. Great potential for development in the right environment.",
    stats: {
      appearances: 15,
      goals: 8,
      assists: 2,
      minutesPlayed: "900",
      shotsOnTarget: 22,
      passAccuracy: "70%",
    },
    strengths: ["Speed", "Finishing", "Body strength"],
    areasToImprove: ["Tactical awareness", "First touch", "Heading"],
    contractStatus: "Available for Loan/Transfer",
    relocation: true,
    preferredLeagues: ["Ligue 1", "Serie A"],
  },
  {
    id: "LP-612",
    name: "Gabriel Rossi",
    position: "Midfielder",
    age: 19,
    country: "Argentina",
    level: "Wonderkid",
    status: "Scouted",
    trend: "Improving",
    image: "https://i.pravatar.cc/150?u=gabriel",
    bio: "Young creative spark with exceptional dribbling in tight spaces. Already attracting interest from major European clubs.",
    stats: {
      appearances: 18,
      goals: 5,
      assists: 9,
      minutesPlayed: "1,450",
      shotsOnTarget: 28,
      passAccuracy: "84%",
    },
    strengths: ["Agility", "Vision", "Creativity"],
    areasToImprove: [
      "Physical strength",
      "Defensive contribution",
      "Experience",
    ],
    contractStatus: "Youth Contract - High Release Clause",
    relocation: true,
    preferredLeagues: ["Premier League", "Serie A"],
  },
  {
    id: "LP-735",
    name: "Erik Jørgensen",
    position: "Defender",
    age: 28,
    country: "Norway",
    level: "Veteran",
    status: "Free Agent",
    trend: "Declining",
    image: "https://i.pravatar.cc/150?u=erik",
    bio: "Experienced center-back with over 200 pro appearances. Strong leader who organizes the backline effectively.",
    stats: {
      appearances: 22,
      goals: 1,
      assists: 0,
      minutesPlayed: "1,980",
      shotsOnTarget: 4,
      passAccuracy: "80%",
    },
    strengths: ["Experience", "Communication", "Aerial ability"],
    areasToImprove: ["Sprint speed", "Agility", "Injury recovery"],
    contractStatus: "Free Agent - Looking for final challenge",
    relocation: true,
    preferredLeagues: ["Championship", "MLS"],
  },
  {
    id: "LP-844",
    name: "Liam O'Connor",
    position: "Midfielder",
    age: 22,
    country: "Ireland",
    level: "Pro",
    status: "Seeking Loan",
    trend: "Improving",
    image: "https://i.pravatar.cc/150?u=liam",
    bio: "Tenacious defensive midfielder who breaks up play effectively. Good range of passing to start counter-attacks.",
    stats: {
      appearances: 24,
      goals: 2,
      assists: 3,
      minutesPlayed: "1,850",
      shotsOnTarget: 10,
      passAccuracy: "86%",
    },
    strengths: ["Tackling", "Work rate", "Interceptions"],
    areasToImprove: [
      "Goal contribution",
      "Discipline (Yellow cards)",
      "Long range shooting",
    ],
    contractStatus: "Available for Loan",
    relocation: true,
    preferredLeagues: ["Scottish Premiership", "League One"],
  },
  {
    id: "LP-951",
    name: "Matheus Oliveira",
    position: "Winger",
    age: 24,
    country: "Portugal",
    level: "Pro",
    status: "Seeking Transfer",
    trend: "Improving",
    image: "https://i.pravatar.cc/150?u=matheus",
    bio: "Skilful winger with direct running style. Excellent crosser of the ball and threat on the counter.",
    stats: {
      appearances: 27,
      goals: 7,
      assists: 10,
      minutesPlayed: "2,150",
      shotsOnTarget: 32,
      passAccuracy: "76%",
    },
    strengths: ["Crossing", "One-on-one dribbling", "Acceleration"],
    areasToImprove: [
      "Defensive tracking back",
      "Weak foot usage",
      "Decision making in box",
    ],
    contractStatus: "Listed for Transfer",
    relocation: true,
    preferredLeagues: ["Premier League", "Primeira Liga"],
  },
];
